### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by Bondok6** [Leboroz/api-web-app#24]
# HI @gdumani and @gdumani 

## To Highlight
- Your code is clean 
- I liked your design

## Suggestions
- Suggest using `async` and `await`  to solve this issue.

**Comment by andres-condezo** [comment]
Hi @gdumani and @Leboroz, 
 
## Highlights
- I liked the way you use deconstruction within the parameters of the same function arrow 🟢 

![](https://64.media.tumblr.com/5a97be1dba647633e37cce9b571e30d2/tumblr_mnvx967abB1sr1ki0o1_250.gifv) 

Cheers and Happy coding!
